#!/usr/bin/python3
'''
script that takes in a letter and sends a POST request to http://0.0.0.0:5000/search_user
with the letter as a parameter.

The letter must be sent in the variable q
If no argument is given, set q=""
If the response body is properly JSON formatted and not empty, display the id and name like this: [<id>] <name>
Otherwise:
Display Not a valid JSON if the JSON is invalid
Display No result if the JSON is empty
You must use the package requests and sys
You are not allowed to import packages other than requests and sys
Please test your script in the container provided, using the web server running on
port 5000. All JSON generated by this server are random.
'''

#Import modules
import requests
import sys
#Get the letter (if given)
if len(sys.argv) > 1:
    q = sys.argv[1]  # Take the first argument
else:
    q = ""           # If nothing is given, use empty string
#Prepare the POST request
url = "http://0.0.0.0:5000/search_user"
data = {'q': q}
#Send the POST request and get the response
response = requests.post(url, data=data)
# Try to convert the response to JSON
try:
    json_data = response.json()
    if json_data:
        print(f"[{json_data.get('id')}] {json_data.get('name')}")
    else:
        print("No result")
except ValueError:
    print("Not a valid JSON")
